In [1]:
import numpy as np
from sklearn import svm

X = np.array([[3, 0.5], [5, -1], [1, -1], [6, 2], [4, 2], [-2, -2.5], [-2, 3], [-5, 1], [-3, -2], [-4, 2], [1, 2]])
y = np.array([1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1])  # Blue points (class 1), Red points (class 0) as -1

# Create an SVM classifier with a hard margin (What is hard margin?, what is C parameter? We'll learn about it later)
clf = svm.SVC(kernel='linear', C=1e5)

# Fit the classifier to the data
clf.fit(X, y)

# You can now use the trained classifier to make predictions on new data
# Get the coefficients (weights) of the hyperplane
coefficients = clf.coef_
print("Weights:", coefficients)

# Get the bias (intercept) of the hyperplane
intercept_ = clf.intercept_
print("Bias:", intercept_)

# Get the Support Vectors
support_vectors = clf.support_vectors_
print("Support Vectors:\n", support_vectors)

Weights: [[ 0.99986773 -0.66640213]]
Bias: [-0.6665344]
Support Vectors:
 [[-2.  -2.5]
 [ 1.   2. ]
 [ 1.  -1. ]]


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

def classify_point(x):
    """
    Classify a point as 'Blue' or 'Red' using the hyperplane from the SVM.
    
    Args:
    x (array-like): The coordinates of the point as a tuple or list.

    Returns:
    str: 'Blue' if the point is above the hyperplane, 'Red' otherwise.
    """
    w = np.array([coefficients[0][0], coefficients[0][1]])  # Coefficients of the hyperplane
    b = intercept_[0]  # Intercept of the hyperplane
    
    # Hyperplane equation using dot product: np.dot(w, x) + b
    result = np.dot(w, x) + b
    
    return result

# Function to plot the point and the hyperplane
def plot_point(x1, x2):
    point = np.array([x1, x2])
    result = classify_point(point)
    classification = 'Blue' if result >= 0 else 'Red'

    # Plotting
    plt.figure(figsize=(8, 6))
    plt.axhline(0, color='grey', lw=1)
    plt.axvline(0, color='grey', lw=1)

    # Plotting the hyperplane
    x_vals = np.linspace(-10, 10, 100)
    y_vals = (-(coefficients[0][0] * x_vals) - intercept_[0]) / coefficients[0][1]
    plt.plot(x_vals, y_vals, 'green', label='Hyperplane')

    #Plotting the line that goes through the support vector with class 1
    y_vals_1 = (1-(coefficients[0][0] * x_vals) - intercept_[0]) / coefficients[0][1]
    plt.plot(x_vals, y_vals_1, 'purple', label='Line that goes through support vector with class 1', linestyle='--')
    
    #Plotting the line that goes through the support vector with class -1
    y_vals_2 = (-1-(coefficients[0][0] * x_vals) - intercept_[0]) / coefficients[0][1]
    plt.plot(x_vals, y_vals_2, 'purple', label='Line that goes through support vector with class -1', linestyle='--')

    # Plotting the point
    plt.scatter(x1, x2, color=classification.lower(), label=f'Point ({x1}, {x2})')
    plt.xlim(-10, 10)
    plt.ylim(-10, 10)
    plt.xlabel('$x_1$')
    plt.ylabel('$x_2$')
    plt.title('Point Classification with Hyperplane')
    plt.legend()
    plt.show()

    return classification, result

# Interactive function
def interactive_classification(x1=(-10.0, 10.0), x2=(-10.0, 10.0)):
    classification, result = plot_point(x1, x2)
    print(f"The point ({x1}, {x2}) is classified as '{classification}' with result {result:.4f}.")

interact(interactive_classification)

interactive(children=(FloatSlider(value=0.0, description='x1', max=10.0, min=-10.0), FloatSlider(value=0.0, de…

<function __main__.interactive_classification(x1=(-10.0, 10.0), x2=(-10.0, 10.0))>

In [3]:
import numpy as np
from sklearn import svm

X = np.array([
    [3.00, 1.00], [3.07, 1.18], [1.48, -2.39], [6.77, -2.18], [5.83, -0.21], [3.67, -3.26], 
    [3.58, 3.02], [-0.09, -3.42], [1.45, -1.58], [2.79, 1.18], [6.10, -1.52], [6.46, -0.11], 
    [6.70, -2.54], [1.30, -0.30], [1.75, -3.09], [2.80, 0.97], [3.28, 2.76], [0.59, -1.67], 
    [6.20, -1.50], [6.52, 0.18], [3.28, 2.76], [0.59, -1.67], [6.20, -1.50], [6.52, 0.18], 
    [4.06, 0.75], [5.10, -0.73], [4.89, -0.03], [6.31, 0.89], [5.54, 0.30], [4.66, 1.55], 
    [5.48, -2.17], [4.27, -1.70], [5.65, -1.32], [4.84, -2.93], [5.38, 0.58], [5.00, 1.34], 
    [4.71, 0.84], [5.96, -0.79], [4.54, 0.30], [5.73, -0.61], [-2.00, 3.00], [-5.80, 3.44], 
    [-3.69, 3.85], [-1.63, 3.56], [-4.67, -0.32], [-4.58, 1.83], [-3.81, 3.38], [-2.90, 0.41], 
    [-4.69, -2.15], [-4.75, -3.36], [-2.40, 1.72], [-1.91, 2.53], [-5.73, 1.52], [-5.70, -0.21], 
    [-5.87, -2.00], [-1.35, 2.96], [-4.71, -2.75], [-6.62, 0.79], [-5.32, 1.10], [-1.89, 1.76]
])


y = np.array([
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
])


# Create an SVM classifier with a hard margin (What is hard margin?, what is C parameter? We'll learn about it later)
clf = svm.SVC(kernel='linear', C=1e5)

# Fit the classifier to the data
clf.fit(X, y)

# You can now use the trained classifier to make predictions on new data
# Get the coefficients (weights) of the hyperplane
coefficients = clf.coef_
print("Weights:", coefficients)

# Get the bias (intercept) of the hyperplane
intercept_ = clf.intercept_
print("Bias:", intercept_)

# Get the Support Vectors
support_vectors = clf.support_vectors_
print("Support Vectors:\n", support_vectors)

Weights: [[ 0.46068003 -0.25749064]]
Bias: [0.32359972]
Support Vectors:
 [[-4.75 -3.36]
 [-1.89  1.76]
 [ 1.3  -0.3 ]]


In [4]:
import numpy as np
from sklearn import svm

X = np.array([
    [3.00, 1.00], [3.07, 1.18], [1.48, -2.39], [6.77, -2.18], [5.83, -0.21], [3.67, -3.26], 
    [3.58, 3.02], [-0.09, -3.42], [1.45, -1.58], [2.79, 1.18], [6.10, -1.52], [6.46, -0.11], 
    [6.70, -2.54], [1.30, -0.30], [1.75, -3.09], [2.80, 0.97], [3.28, 2.76], [0.59, -1.67], 
    [6.20, -1.50], [6.52, 0.18], [3.28, 2.76], [0.59, -1.67], [6.20, -1.50], [6.52, 0.18], 
    [4.06, 0.75], [5.10, -0.73], [4.89, -0.03], [6.31, 0.89], [5.54, 0.30], [4.66, 1.55], 
    [5.48, -2.17], [4.27, -1.70], [5.65, -1.32], [4.84, -2.93], [5.38, 0.58], [5.00, 1.34], 
    [4.71, 0.84], [5.96, -0.79], [4.54, 0.30], [5.73, -0.61], [-2.00, 3.00], [-5.80, 3.44], 
    [-3.69, 3.85], [-1.63, 3.56], [-4.67, -0.32], [-4.58, 1.83], [-3.81, 3.38], [-2.90, 0.41], 
    [-4.69, -2.15], [-4.75, -3.36], [-2.40, 1.72], [-1.91, 2.53], [-5.73, 1.52], [-5.70, -0.21], 
    [-5.87, -2.00], [-1.35, 2.96], [-4.71, -2.75], [-6.62, 0.79], [-5.32, 1.10], [-1.89, 1.76],
    [0, -0.25]
])


y = np.array([
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1
])


# Create an SVM classifier with a hard margin (What is hard margin?, what is C parameter? We'll learn about it later)
clf = svm.SVC(kernel='linear', C=1e5)

# Fit the classifier to the data
clf.fit(X, y)

# You can now use the trained classifier to make predictions on new data
# Get the coefficients (weights) of the hyperplane
coefficients = clf.coef_
print("Weights:", coefficients)

# Get the bias (intercept) of the hyperplane
intercept_ = clf.intercept_
print("Bias:", intercept_)

# Get the Support Vectors
support_vectors = clf.support_vectors_
print("Support Vectors:\n", support_vectors)

Weights: [[ 1.50867809 -0.78160554]]
Bias: [-1.19552197]
Support Vectors:
 [[ 0.   -0.25]
 [ 1.3  -0.3 ]
 [ 0.59 -1.67]]


In [5]:
import numpy as np
from sklearn import svm

X = np.array([
    [3.00, 1.00], [3.07, 1.18], [1.48, -2.39], [6.77, -2.18], [5.83, -0.21], [3.67, -3.26], 
    [3.58, 3.02], [-0.09, -3.42], [1.45, -1.58], [2.79, 1.18], [6.10, -1.52], [6.46, -0.11], 
    [6.70, -2.54], [1.30, -0.30], [1.75, -3.09], [2.80, 0.97], [3.28, 2.76], [0.59, -1.67], 
    [6.20, -1.50], [6.52, 0.18], [3.28, 2.76], [0.59, -1.67], [6.20, -1.50], [6.52, 0.18], 
    [4.06, 0.75], [5.10, -0.73], [4.89, -0.03], [6.31, 0.89], [5.54, 0.30], [4.66, 1.55], 
    [5.48, -2.17], [4.27, -1.70], [5.65, -1.32], [4.84, -2.93], [5.38, 0.58], [5.00, 1.34], 
    [4.71, 0.84], [5.96, -0.79], [4.54, 0.30], [5.73, -0.61], [-2.00, 3.00], [-5.80, 3.44], 
    [-3.69, 3.85], [-1.63, 3.56], [-4.67, -0.32], [-4.58, 1.83], [-3.81, 3.38], [-2.90, 0.41], 
    [-4.69, -2.15], [-4.75, -3.36], [-2.40, 1.72], [-1.91, 2.53], [-5.73, 1.52], [-5.70, -0.21], 
    [-5.87, -2.00], [-1.35, 2.96], [-4.71, -2.75], [-6.62, 0.79], [-5.32, 1.10], [-1.89, 1.76],
    [1, -1]
])


y = np.array([
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    1,1, 1,1,1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,
    -1
])


# Create an SVM classifier with a hard margin (What is hard margin?, what is C parameter? We'll learn about it later)
clf = svm.SVC(kernel='linear', C=1e7)

# Fit the classifier to the data
clf.fit(X, y)

# You can now use the trained classifier to make predictions on new data
# Get the coefficients (weights) of the hyperplane
coefficients = clf.coef_
print("Weights:", coefficients)

# Get the bias (intercept) of the hyperplane
intercept_ = clf.intercept_
print("Bias:", intercept_)

# Get the Support Vectors
support_vectors = clf.support_vectors_
print("Support Vectors:\n", support_vectors)

Weights: [[ 1.37253163 -0.21883039]]
Bias: [-0.39185024]
Support Vectors:
 [[ 1.   -1.  ]
 [-0.09 -3.42]
 [ 1.3  -0.3 ]
 [ 1.75 -3.09]
 [ 0.59 -1.67]]


In [6]:
import numpy as np

w = np.array([0.46068003, -0.25749064])
x = np.array([-4, 0])
b = 0.32359972

1 - -1.0 * (w.dot(x) + b)

-0.5191204

In [7]:
import numpy as np

w = np.array([0.46068003, -0.25749064])
x = np.array([1, 1])
b = 0.32359972

1 - 1.0 * (w.dot(x) + b)

0.47321089000000005