In [1]:
import numpy as np

# Scalar
x_scalar = 6

# Vector
x_vector = np.array([1, 2])

# Multiplication of Scalar and Vector
scalar_mult_vector = 2 * x_vector
print("Multiplication of scalar and vector:", scalar_mult_vector)

# Addition of Vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
vector_sum = vector_a + vector_b
print("Addition of vectors:", vector_sum)

# Vector Dot Product
dot_product = np.dot(vector_a, vector_b)
print("Dot product of vectors:", dot_product)

# Matrix
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Matrix Dimension
print("Matrix A dimension:", matrix_a.shape)

# Matrix Addition (only possible if dimensions match)
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])
matrix_sum = matrix_a + matrix_c
print("Matrix addition result:\n", matrix_sum)

# Matrix Dot Product
matrix_dot_product = np.dot(matrix_a, matrix_b)
print("Matrix dot product:\n", matrix_dot_product)

# Matrix Transpose
matrix_transpose = matrix_a.T
print("Matrix transpose:\n", matrix_transpose)

# Identity Matrix
identity_2x2 = np.eye(2)
identity_3x3 = np.eye(3)
print("2x2 Identity Matrix:\n", identity_2x2)
print("3x3 Identity Matrix:\n", identity_3x3)

# Inverse Matrix
A = np.array([[2, 1], [3, 4]])
A_inv = np.linalg.inv(A)
print("Inverse of matrix A:\n", A_inv)

# Solving Linear Equation
# 2x + y = 5
# 3x + 4y = 10
B = np.array([5, 10])
solution = np.linalg.solve(A, B)
print("Solution of linear equations (price of apple and orange):", solution)

# Sigma Notation
x = np.array([1, 2, 3, 4, 5])
sigma_sum = sum(x[i] for i in range(len(x)))
print("Sigma notation result:", sigma_sum)

# Product Notation
product_result = 1
for i in range(len(x)):
    product_result *= x[i]
print("Product notation result:", product_result)


Multiplication of scalar and vector: [2 4]
Addition of vectors: [5 7 9]
Dot product of vectors: 32
Matrix A dimension: (2, 3)
Matrix addition result:
 [[ 2  4  6]
 [ 8 10 12]]
Matrix dot product:
 [[ 58  64]
 [139 154]]
Matrix transpose:
 [[1 4]
 [2 5]
 [3 6]]
2x2 Identity Matrix:
 [[1. 0.]
 [0. 1.]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Inverse of matrix A:
 [[ 0.8 -0.2]
 [-0.6  0.4]]
Solution of linear equations (price of apple and orange): [2. 1.]
Sigma notation result: 15
Product notation result: 120
