In [1]:
# Unsqueeze demo
import torch

# Unsqueeze
x = torch.tensor([1, 2, 3, 4])
print(x.shape)
print(x)
print()

x = x.unsqueeze(0)
print(x.shape)
print(x)
print()

x = x.unsqueeze(1)
print(x.shape)
print(x)
print()

torch.Size([4])
tensor([1, 2, 3, 4])

torch.Size([1, 4])
tensor([[1, 2, 3, 4]])

torch.Size([1, 1, 4])
tensor([[[1, 2, 3, 4]]])



In [2]:
import torch

# Unsqueeze
x = torch.tensor([1, 2, 3, 4])
print(x.shape)
print(x)
print()

x = x.unsqueeze(0)
print(x.shape)
print(x)
print()

x = x.unsqueeze(2)
print(x.shape)
print(x)
print()

torch.Size([4])
tensor([1, 2, 3, 4])

torch.Size([1, 4])
tensor([[1, 2, 3, 4]])

torch.Size([1, 4, 1])
tensor([[[1],
         [2],
         [3],
         [4]]])



In [3]:
# Squeeze demo
import torch

x = torch.tensor([[[1, 2, 3, 4]]])

print(x.shape)
print(x)
print()

x = x.squeeze(0)
print(x.shape)
print(x)
print()

torch.Size([1, 1, 4])
tensor([[[1, 2, 3, 4]]])

torch.Size([1, 4])
tensor([[1, 2, 3, 4]])



In [4]:
import torch

x = torch.tensor([[[1, 2, 3, 4]]])

print(x.shape)
print(x)
print()

x = x.squeeze()
print(x.shape)
print(x)
print()

torch.Size([1, 1, 4])
tensor([[[1, 2, 3, 4]]])

torch.Size([4])
tensor([1, 2, 3, 4])



In [5]:
import torch

x = torch.ones(2, 1, 2)

print(x.shape)
print(x)
print()

x = x.squeeze(1)

print(x.shape)
print(x)
print()

torch.Size([2, 1, 2])
tensor([[[1., 1.]],

        [[1., 1.]]])

torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])



In [6]:
import torch

x = torch.ones(2, 1, 2)

print(x.shape)
print(x)
print()

x = x.squeeze(2)

print(x.shape)
print(x)
print()

torch.Size([2, 1, 2])
tensor([[[1., 1.]],

        [[1., 1.]]])

torch.Size([2, 1, 2])
tensor([[[1., 1.]],

        [[1., 1.]]])



In [7]:
## Reshape demo
import torch

x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x.shape)
print(x)
print()

x = x.reshape(4, 2)
print(x.shape)
print(x)
print()

torch.Size([2, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])



In [8]:
import torch

x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

x = x.reshape(2, 2, 2)
print(x.shape)
print(x)
print()

x = x.reshape(2, 2, 2, 1)
print(x.shape)
print(x)
print()

x = x.reshape(8, 1)
print(x.shape)
print(x)
print()

torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

torch.Size([2, 2, 2, 1])
tensor([[[[1],
          [2]],

         [[3],
          [4]]],


        [[[5],
          [6]],

         [[7],
          [8]]]])

torch.Size([8, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])



In [9]:
# Flatten demo

import torch

x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
x = x.flatten()
print(x.shape)
print(x)
print()

torch.Size([8])
tensor([1, 2, 3, 4, 5, 6, 7, 8])



In [10]:
# Multi-dimension tensor

import torch
x = torch.ones(2, 2, 2, 2)
print(x.shape)
print(x)
print()

x = x.flatten()
print(x.shape)
print(x)
print()

torch.Size([2, 2, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

torch.Size([16])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])



In [11]:
# Permute demo

import torch

x = torch.ones(2, 3, 4)
print(x.shape)
print(x)
print()

x = x.permute(2, 0, 1)
print(x.shape)
print(x)
print()

torch.Size([2, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

torch.Size([4, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

